// Add or remove words here — the ticker will randomly pick 3 at a time
const tickerWords = [
    "Clever 🧠",
    "Simple 📄",
    "Powerful 💪",
    "Intuitive 🎯",
    "Modern 🆕",
    "Fast ⚡",
    "Secure 🔒",
    "Flexible 🔄",
    "Affordable 💰",
    "Reliable 🛡️",
    "New ✨",
    "Modern 🆕",
    "Innovative 💡",
    "Efficient ⚙️",
    "Scalable 📈",
    "User-friendly 🙂",
    "Fresh 🌿",
    "GDPR ✅",
    "Payroll Ready 💼",
    "Reporting 📊",
    "Time Saving ⏱️",
    "Streamlined 🚀",
    "Comprehensive 📚",
    "Customizable 🛠️",
    "Cloud ☁️",
    "Mobile 📱",
    "SaaS 🌐"
];
